CREATE TABLE accounts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    stage TEXT,
    website TEXT NOT NULL,
    industry TEXT,
    territory TEXT,
    employee_range TEXT,
    phone TEXT NOT NULL,
    fax TEXT,
    linkedin TEXT,
    user_id INTEGER 
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);


