CREATE TABLE contacts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER 
        REFERENCES accounts(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER 
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    title TEXT,
    phone TEXT NOT NULL,
    email TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);


